apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-monitoring
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluentbit
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:latest
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
        volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
          readOnly: true
        - name: lua-scripts
          mountPath: /fluent-bit/scripts
          readOnly: true
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
          items:
          - key: fluent-bit.conf
            path: fluent-bit.conf
          - key: input-kubernetes.conf
            path: input-kubernetes.conf
          - key: filters.conf
            path: filters.conf
          - key: outputs.conf
            path: outputs.conf
          - key: functions.lua
            path: functions.lua
      - name: lua-scripts
        configMap:
          name: fluent-bit-config
          items:
          - key: functions.lua
            path: functions.lua            
      - name: varlog
        hostPath:
          path: /var/log            
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers          