apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
spec:
  ports:
  - port: 8123
    targetPort: 8123
    name: http
  - port: 9000
    targetPort: 9000
    name: native
  selector:
    app: clickhouse
  type: ClusterIP
